config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "welcome/index", to: "welcome#index"
  get "welcome/about", to: "welcome#about"

  resources :users
  root "welcome#index"

  get 'signup', to: "users#new"
  post 'users', to: 'users#create'

  resources :articles

  resources :users, except: [:new]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title , presence: true , length: {minimum:3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save{ self.email = email.downcase}
   validates :username, presence:true,
             uniqueness:{case_sensitive:false},
             length: {minimum: 3, maximum: 25}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence:true , length: {maximum: 105},
             uniqueness: {case_sensitive: false},
             format: {with: VALID_EMAIL_REGEX}
   has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:edit,:update,:show,:destroy]
  def index
    @articles = Article.all
  end

  def new
      @article = Article.new
  end

  def create
    # debugger
    #to values sent by form
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end

  end

  def show
    @article = Article.find(params[:id])
    @user = @article.user
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article successfuly deleted"
    redirect_to articles_path
  end

  def edit
  end

  def update
    if @article.update(article_params)
        flash[:notice]= "Article updated successfully"
        redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title,:description)
    end
end

app/controllers/concerns/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:edit,:update,:show,:destroy]
  def index
    @articles = Article.all
  end

  def new
      @article = Article.new
  end

  def create
    #to values sent by form
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end

  end

  def show
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article successfuly deleted"
    redirect_to articles_path
  end

  def edit
  end

  def update
    if @article.update(article_params)
        flash[:notice]= "Article updated successfully"
        redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title,:description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "You account updated successfully"
      redirect_to articles_path
    else
        render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username)
  end
end

app/views/articles/_form.html.erb
<br/>
<% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
    <% end %>
<% end %>
<br/>
<%= form_for @article do |f|  %>
    <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description %>
    </p>
    <%= f.submit %>

<% end %>
<%= link_to "Back" , articles_path %>
<br/>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= link_to "About", welcome_about_path %>
<%= link_to "Home", root_path %>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Article List</h1>
<%= link_to "Home" , root_path %>
<%= link_to "Create Article" , new_article_path %>
<br/>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>actions</th>
  </tr>
  <% @articles.each do |a| %>

    <tr>

      <td>
        <%= a.title %>
      </td>
      <td>
        <%= a.description %>
        <br/>
        <small>Created by :
          <%= a.user.username if a.user %>,
          Created at : <%= time_ago_in_words(a.created_at) %> ago ,
          Updated at : <%= time_ago_in_words(a.updated_at) %> ago
        </small>
      </td>
      <td>
        <%= link_to "edit", edit_article_path(a) %>
        <%= link_to "show", article_path(a) %>
        <%= link_to "deleted", article_path(a), method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<h2>New Article</h2>
<%= link_to "About", welcome_about_path %>
<%= link_to "Home", root_path %>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>


<p><%=  link_to gravatar_for(@user), user_path(@user) %></p>
<p><%= @user.email %></p>
<p><%= link_to @user.username , user_path(@user) %></p>

<p>Title : <%= @article.title %></p>
<p>Description : <%= @article.description %></p>
<br/>
<%= link_to "edit", edit_article_path(@article) %> |
<%= link_to "Back" , articles_path %>

app/views/layouts/_messages.html.erb
<ul>
  <% flash.each do |name,msg| %>
      <li><%= msg %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% render 'layouts/messages' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
    <% end %>
<% end %>
<br/>
<%= form_for @user do |f|  %>
    <p>
      <%= f.label :username %><br/>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :email %><br/>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br/>
      <%= f.text_field :password %>
    </p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update") %>

<% end %>
<%= link_to "Back" , root_path %>
<br/>

app/views/users/edit.html.erb
<h1>Edit Your Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All bloggers</h1>

<% @users.each do |user| %>
  <p><%=  link_to gravatar_for(user), user_path(user) %></p>
    <p><%= user.email %></p>
    <p><%= link_to user.username , user_path(user) %></p>
    <p><%= pluralize(user.articles.count , "Article") if user.articles %></p>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Show user</h1>
<%= gravatar_for @user %>
<br/>
<%= @user.username %>
<br/>
<h2>
<%= @user.username %>'s Artices
</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>actions</th>
  </tr>
  <% @articles.each do |a| %>
      <tr>
        <td>

          <%= a.title %></td>
        <td>
          <%= a.description %>
          <br/>
          <small>Created by :
            <%= a.user.username if a.user %>,
            Created at : <%= time_ago_in_words(a.created_at) %> ago ,
            Updated at : <%= time_ago_in_words(a.updated_at) %> ago
          </small>
        </td>
        <td>
          <%= link_to "edit", edit_article_path(a) %>
          <%= link_to "show", article_path(a) %>
          <%= link_to "deleted", article_path(a), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/welcome/about.html.erb
<h2>My about</h2>
<%= link_to "Home", root_path %>

app/views/welcome/index.html.erb
<h2>My home</h2>
<%= link_to "About", welcome_about_path %>
<%= link_to "Alpha Blog", articles_path %>